### ISSUE TITLE
Mobile navigation

### ISSUE THREAD

**Issue by victorvalle** [liferay/lexicon-site#27]
Navigation with menu doesn't work after first use.

Steps to reproduce.
1. Home search bar: alerts
2. Intro
3. Click on burger menu
4. Navigate to another page: collapsible search
5. Click on burger menu. The navigation panel is not being displayed.

**Comment by natecavanaugh** [comment]
Heya Victor,
Okay, I figured out what's going on. I'm assuming you're running npm less than 5.0.0, which in 5.0 they made a big change to how dependencies are grabbed and are much more stable across different installs (so it only installs what you've explicitly stated).

Since (I'm assuming) you're running an earlier npm, it fetched down the latest minor version of the metal-toggler which is 2.2.0. In the package.json, though it says 2.0.0, so my local installs were using 2.0.0, and whenever I would deploy, it would use that one (and that's the one that's working).

Metal-toggler 2.2.0 shouldn't have been made a minor version, since it broke API compatibility by changing the CSS classes.

Anyways, I'm pushing up a fix to handle this, but I'd highly recommend upgrading to node 8 and npm 5 so you can be more sure that you're installing what everyone else is :)

Thanks Victor!

**Comment by marcoscv-work** [comment]
Hey guys, I think there is another issue related with mobile navigation.

Navigation menu only works fine when the page has been refreshed, after that if you navigate for more than one page the menu cannot be opened.

It looks more related with sennajs I think.

**Comment by natecavanaugh** [comment]
Heya @marcoscv thanks for reopening this one. It actually appears to be happening on all Electric based sites, including WeDeploy.

From what I can tell, it's something inside of Electric, specifically around these places:
[Here](https://github.com/electricjs/electric/blob/1e16ba48cc3bb728786a87a2ada1ee9e1830f9d5/lib/templates/metal-render.tpl#L12-L14) and [here](https://github.com/electricjs/electric/blob/1e16ba48cc3bb728786a87a2ada1ee9e1830f9d5/lib/templates/vendor.tpl#L15-L17).

I'm going to dump all this info here, just so it's recorded and we can get it to the best people later, but at least it's here for reference.What's happening is that each page is a metal component, and those blocks of code are trying to keep track of those components between page loads so they can `dispose` of them (basically, removing their interactions from the page).
But for whatever reason, the [event listener here](https://github.com/electricjs/electric/blob/1e16ba48cc3bb728786a87a2ada1ee9e1830f9d5/lib/templates/vendor.tpl#L57-L60) fires randomly out of order to the execution of the script block in metal-render.tpl.

What this means is that randomly, it fires out of order, and instead of disposing of the previous component properly, it keeps both of them activated, meaning that there are two sidenavigation listeners and when they both call toggle, it opens and closes immediately as if nothing were happening.

I'll dig a bit more into it and see if there's something that can be sent over to the electric team as a pull, or at the very least a detailed issue.

I'll update this ticket with info as soon as I have it.

Thanks again Marcos and Victor :)

**Comment by natecavanaugh** [comment]
Hey guys @victorvalle and @marcoscv 
This is fixed in the latest electric and electric-cli. To update to the latest:
```
npm install -g electric-cli@latest
```
Can you guys also ask the same of anyone who is deploying the site, because if they use the older electric-cli, the bug will just reappear.

Thanks guys,
