### ISSUE TITLE
News: distance between date and title of the new.

### ISSUE THREAD

**Issue by victorvalle** [liferay/lexicon-site#28]
The distance between both text must be reduced and date text style shouldn't be an h5. It should have the same style but not the tag.

<img width="834" alt="captura de pantalla 2017-06-25 a las 20 30 25" src="https://user-images.githubusercontent.com/21121115/27518661-8244a0d4-59e5-11e7-8a68-b0dfc1933a96.png">
A style file is missing for this page.

**Comment by natecavanaugh** [comment]
@victorvalle I've gone ahead and created a markdown parser for this piece so that way it will be more semantic.

What I've done is to make it so that each date just needs to have this:

`<time>January 31st, 2017</time>`

So basically, just wrap the date with the `<time>` tag, and it will place it there and if it can parse the date (which, as long as we follow the format above, it shouldn't have any issues), it will add a `datetime=""` attribute.

I've also fixed the spacing, but you didn't mention what the spacing should be, so I've defaulted it to looking like the below:
<img width="686" alt="screenshot 2017-06-27 15 46 09" src="https://user-images.githubusercontent.com/116871/27613327-c92ccbdc-5b4f-11e7-8d4c-c336eff7f6d7.png">

Feel free to modify it however you guys prefer, and if you'd rather not have the time element (or have it be some other element), don't hesitate to let me know, and I can either modify this or roll it back out.

Thanks Victor!
